---
title: "Weather Data Plots- NY"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(rnoaa)
library(ggplot2)
library(plotly)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Scatter Plot

```{r}

#making the data frame
stations <- ghcnd_stations()
nystationids <-  stations |> 
  filter(state == "NY") |>
  slice(1:6) |>
  distinct(id)

nydat <- meteo_pull_monitors(nystationids$id, 
                             date_min = "2013-01-01", 
                             date_max = "2023-12-31", 
                             var = c("PRCP", "SNOW", "SNWD")) |>
  select(-id) |>
  filter(!(is.na("PRCP") & is.na("SNOW") & is.na("SNWD")))
save(nystationids, nydat, file = "nynoaadat.RData")

#making a scatterplot
scatter_ggplot = 
  nydat |>
  ggplot(aes(x = date, y = prcp, color= prcp)) +
  geom_point(alpha = 0.666) +
  scale_color_gradient(low = "lightblue", high = "navy") +
  labs(x = "Date", y = "Precipition", title = "Precipitation over time") +
  coord_cartesian()

ggplotly(scatter_ggplot, tooltip = c("x", "y"))
```

Column {data-width=450}
-----------------------------------------------------------------------

### Bar Plot

```{r}

#manipulating to have years
year_ny_dat = nydat |>
  mutate(year = nydat$year <- format(nydat$date, "%Y")) |>
  group_by(year) |>
  summarise(total_prcp = sum(prcp, na.rm = TRUE))

#making the bar plot
bar_ggplot = 
  year_ny_dat |>
  ggplot(aes(x=year, y=total_prcp, fill=year)) +
  geom_bar(stat = "identity") +
  labs(x= "Year", y = "Total Precipitation", title = "Plot for Year Wise Total Precipitation")
  

ggplotly(bar_ggplot, tooltip = c("x", "y"))

```

### Line Plot

```{r}

#removing na/0 snow and snwd
nydat1 <- nydat |>
  mutate(snow = ifelse(snow == 0, NA, snow), snwd = ifelse(snwd == 0, NA, snwd)) |>
  filter(!is.na(snow) & !is.na(snwd))

#making a model and variables for intercept and slope
lm_model <- lm(snwd ~ snow, data = nydat1)
coefficients <- coef(lm_model)
intercept <- coefficients[1]
slope <- coefficients[2]

#making a line plot to compare relationships between snow and snwd
line_plot <- nydat1 |>
  ggplot(aes(x = snow, y = snwd, text = date)) +
  geom_line() +
  geom_abline(linetype = "dotted", intercept = intercept, slope = slope, color = "magenta", lwd = 0.7) +
  labs(y = "Snow Depth (SNWD)", x = "Snow", title = "Relationship Between Snowfall and Snow Depth")
ggplotly(line_plot)
```